### ISSUE TITLE
Validate yaml structure with --combine 

### ISSUE THREAD

**Issue by dimakievua** [open-policy-agent/conftest#153] opened 2019-11-07 10:16 UTC
Hi, 

I found the strange behavior of `conftest test --combine [files]`. YAML file should be formatted with very strict rule: 
- `---` delimiter at beginning
- `---` delimiter at the end
- **new line** at the end after the last delimiter
Even I have several files with one manifest per file I should all al of this. Otherwise **conftest** just ignore file. If I have several manifests per file it just ignores latest manifest.

Here is an example, I just removed a new line in one file and --- with a new line in another:
```
/project # conftest test -p /policy --combine $( ls | grep yaml | xargs) -i yaml
WARN - Combined - Document 0 of file_copy.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file_copy.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file_copy.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file_copy.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file.yaml and document 0 of file_copy.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 0 of file_copy.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 0 of file_copy.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 0 of file_copy.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
FAIL - Combined - Expected VirtualService hosts virtual-searchconfigservice-redis, be the same as Service name 1virtual-searchconfigservice-redis
FAIL - Combined - Error in ServiceEntry test2, STATIC resolution is not allowed
FAIL - Combined - Error in ServiceEntry test2, namespace should be external, but set internal 
```
and after removal:
```
/project # conftest test -p /policy --combine $( ls | grep yaml | xargs)
WARN - Combined - Document 0 of file.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 0 of file2.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 1 of file2.yaml and document 2 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 0 of file.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 0 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Document 2 of file2.yaml and document 1 of file2.yaml contain a resource of kind ServiceEntry that have conflicting names
WARN - Combined - Expected these values to be different. ServiceEntry name: test2
FAIL - Combined - Expected VirtualService hosts virtual-searchconfigservice-redis, be the same as Service name 1virtual-searchconfigservice-redis
FAIL - Combined - Error in ServiceEntry test2, STATIC resolution is not allowed
FAIL - Combined - Error in ServiceEntry test2, namespace should be external, but set internal 
```

Maybe it reasonable to validate YAML before combine in `conftest` code? Handle absence on `---` and `new line` at the end?

**Comment by boranx** [comment] 2019-11-14 16:34
Thanks for issuing this.
@Salamandastron1 @jpreese, what do you think about this? Should we really check `---` in the first and `new line` at the end?

**Comment by Salamandastron1** [comment] 2019-11-15 16:45
Okay, to make sure I understand the situation correctly. 

Currently while using the `--combine` flag if a file input does not a have `---` at the end of a multi-document then the last *document* in the that file will be ignored.

Correct?

Also thanks for using the flag! It is only through use that we can discover more value and bugs like this :)

**Comment by dimakievua** [comment] 2019-11-18 10:37
@Salamandastron1 hi. Yes, you understand it correctly. The only issue not *last* will be ignored. A document that does not end with delimiter will be parsed as __Object__, not as __Array__ .
Please have a look at the trace from my example. *file2.yaml* has no `---` at the end:
![image](https://user-images.githubusercontent.com/20700407/69045723-1eb9eb00-0a00-11ea-9cd0-f964a6c7bb47.png)

And correct behavior with `---`:
![image](https://user-images.githubusercontent.com/20700407/69045760-2e393400-0a00-11ea-9cba-6a854205f88a.png)

**Comment by Salamandastron1** [comment] 2019-12-16 21:04
@dimakievua could you post the contents of `file.yaml` and `file2.yaml`? I have time to move forward on this but want to recreate the problem accurately

**Comment by KeisukeYamashita** [comment] 2019-12-18 07:45
Agree with @Salamandastron1 . I will be great if you can show your inputs and we can reproduce that kinda errors.

**Comment by xchapter7x** [comment] 2020-07-19 13:51
@dimakievua ,

i know this is an old issue... apologies for the late response. 
I was just looking into this. 
I am able to reproduce the behavior you describe. It is by design.

if you look at the yaml parser here: https://github.com/open-policy-agent/conftest/blob/master/parser/yaml/yaml.go#L17-L23

it is checking to see if there are multiple documents in the yaml file. If there are multiple, then it uses an array, b/c multiple documents make sense to surface in that data structure. If there is only a single document in the yaml file it will use an Object, b/c that is the natural data structure for a yaml object. (this is the assumption/decision on how to treat yaml files currently. Open to explore changing it)

Now when calling combine, it just takes all of the files and appends them to an array. The elements of that array will vary depending upon the datastructure used in the file.

Now that I clearly understand the specific behavior you reference, lets talk about your requested change. 

It would seem that you are looking for a combined array to have a consistent datastructure in each element? I am guessing this makes it easier for you to parse/process when writing policies?
This makes total sense, and i can see how a bit of type safety and consistency would improve the UX here. 


Some possible paths forward:
A) just make a change to your file structure if you want it to be parsed in a specific way. You described your current approach above.

B) Alternatively, we might decide that all yaml files be treated as being an array, to accommodate for multiple documents. If there is only 1 document, it will just be an array of 1 element.


Open to ideas on other approaches or implementations. :)

**Comment by jpreese** [comment] 2020-09-13 19:30
This is very similar to #106 regarding how to interpret multi-doc yamls. Closing this in favor of that discussion as the final decision there will resolve this as well.

**Closed by jpreese** 2020-09-13 19:30 UTC
Labels: enhancement, question
