### ISSUE TITLE
Wrong created date when push to Google container registry

### ISSUE THREAD

**Issue by lopeg** [open-policy-agent/conftest#326] opened 2020-06-22 11:21 UTC
When man uses conftest push to GCR, created date is "Jan 1, 1970"
conftest Version: 0.17.1(Commit: 45177b4)

Expected
current date

In fact
![image](https://user-images.githubusercontent.com/6160482/85281957-286e6a00-b48b-11ea-98d5-0c098330d533.png)

**Comment by Blokje5** [comment] 2020-06-23 19:29
Thanks for reporting this issue @lopeg. I have been able to reproduce this issue:
![image](https://user-images.githubusercontent.com/26072918/85449795-72914180-b598-11ea-9637-2e7a8a25200a.png)

```
conftest push gcr.io/<project-id>/lennard-test:latest -p examples/kubernetes/policy
```

I'll have a look to see what is missing.

**Comment by Blokje5** [comment] 2020-06-23 20:05
I had a quick look into this issue: `conftest push` uses the [ORAS library](https://github.com/deislabs/oras) to push the Rego policies as OCI artifacts. My gut feeling is that the issue is that GCR does not support the OCI image format (It is not listed as one of the [implementors](https://github.com/opencontainers/image-spec/blob/master/implementations.md)). 

However, after quickly glancing at the OCI image format spec and looking at the [annotations section](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) it seems we are also missing some of the required annotations on our manifest. I assume any OCI compliant registry uses the `org.opencontainers.image.created` annotation on the manifest to determine the created date. It should be easy enough to add that annotation to the OCI artifact that is pushed. Adding `oras.WithConfigAnnotations(map[string]string{"org.opencontainers.image.created": "1985-04-12T23:20:50.52Z"}` to the `pushOpts` should do the job. The question is how to fill the date. My feeling is we should use the last modified date of the rego files and use the date of the last file modified. @boranx @jpreese @garethr What is your opinion on this?

**Comment by KeisukeYamashita** [comment] 2020-06-26 17:35
@Blokje5  Have you seen this document?  It says GCR supports OCI image format.
https://cloud.google.com/container-registry/docs/image-formats

**Comment by Blokje5** [comment] 2020-06-26 18:00
@KeisukeYamashita hmmm I wasn't aware. Thanks for pointing that out! I already tried locally adding the annotation to the bundles pushed to GCR, but still it displayed "Jan 1, 1970", which is why I assumed GCR did not support OCI formats. Then again, I should have expected GCR to deny the OCI artifact entirely if it was actually unsupported.

For now I have reported it as an issue on the GCR bug board. Hopefully that will provide some more insight into why the annotation is not displayed as the created date in GCR and how we can fix this issue.

**Comment by KeisukeYamashita** [comment] 2020-06-27 09:03
@Blokje5   Thank you.
I have been able to reproduce this issue too.

I also uploaded my OCI images with `application/vnd.oci.image.manifest.v1+json` annotation but still doesn't work.

![Screen Shot 2020-06-27 at 17 42 00](https://user-images.githubusercontent.com/23056537/85918709-1f710480-b8a0-11ea-9a9a-32655e6d7738.png)

> For now I have reported it as an issue on the GCR bug board. Hopefully that will provide some more insight into why the annotation is not displayed as the created date in GCR and how we can fix this issue.

Thank you. Where did you report this issue? I couldn't find any issues in [GCR IssueTracker](https://issuetracker.google.com/savedsearches/559742) 🤔

**Comment by KeisukeYamashita** [comment] 2020-06-28 04:50
I tried to push to Azure Container Registry(ACR) but the `creation time` was not configurable.
Whatever you configure as `org.opencontainers.image.created`, the container registry uses the timestamp of the `push` event.

![Screen Shot 2020-06-28 at 13 40 13](https://user-images.githubusercontent.com/23056537/85938204-0c187480-b946-11ea-97dd-1b970b15bc13.png)

Therefore, GCR default value(`Jan 1, 1970`) of `Created` timestamp is a bug...

**Comment by garethr** [comment] 2020-07-02 07:59
I've run into this issue with other tooling as well. Specifically with Bazel.

https://github.com/garethr/snykly/blob/master/BUILD#L27

There you need to specify the above `stamp = True`. I'm not sure what that does under the hood, but that's probably the answer to the conundrum.

**Comment by jpreese** [comment] 2020-09-07 15:41
I just tested this as well, and this definitely seems like a GCR issue and should be fixed upstream.

**Closed by jpreese** 2020-09-07 15:41 UTC
Labels: wontfix
