### ISSUE TITLE
Update to 0.23

### ISSUE THREAD

**Issue by zoemac11** [open-policy-agent/conftest#478] opened 2021-02-01 14:05 UTC
When I've updated to version 0.23 I can no long have multiple test files within my policy.

Trying to do a push to ACR and get the following error

```
Error: push bundle: building layers: load: load documents: 1 error occurred during loading: sample_deployments\should_work\data.yaml: merge error

```

Any suggestions how to fix this without delete those files? Its nice to have a couple of file to test against. This was working in version 0.21

**Comment by Blokje5** [comment] 2021-02-14 16:13
Thanks for reporting the issue @zoemac11. Would you be able to provide a reproducible example? It is unclear for me from your description where the issue lies.

**Comment by jpreese** [comment] 2021-02-27 16:52
I think there was a bug in an earlier version of Conftest that wouldn't load _all_ found data files (files with .json, .yml, or .yaml) which is now resolved.

When I've seen this error previously, it was because there were multiple test files, as described here, that conflicted with one another. Behind the scenes, all of the data files get merged together so if there's a conflict when creating the data document this can occur.

As @Blokje5 mentioned, a concrete example of this scenario would be greatly appreciated so we can look into it further!

**Closed** 2021-03-03 08:37 UTC
Labels: bug
