### ISSUE TITLE
test returns 

### ISSUE THREAD

**Issue by Duologic** [open-policy-agent/conftest#426] opened 2020-10-09 07:54 UTC
```
Error: running test: get configurations: get config: open file: open /redacted/path/to/file.yaml: too many open files
```

**Comment by jpreese** [comment] 2020-10-09 13:38
Duplicate of https://github.com/open-policy-agent/conftest/issues/427

**Closed by jpreese** 2020-10-09 13:38 UTC

**Comment by Duologic** [comment] 2020-10-09 17:51
Must have entered too soon and hit back 🙈
