### ISSUE TITLE
Include the file name in system metadata for a policy

### ISSUE THREAD

**Issue by artis3n** [open-policy-agent/conftest#604] opened 2021-08-26 00:58 UTC
Originally filed against opa here (https://github.com/open-policy-agent/opa/issues/3662) but makes more sense to be a specific feature request for conftest.

When evaluating a large set of files, it would be very useful to be able to match against certain known file names as opposed to attempting to examine the input to match that file's expectation. This is for scenarios where we are evaluating a set of policies against a set of arbitrary files and we need the Rego to determine which policies should apply to which input.

Proposal: adding metadata to the global `data` available to a policy when evaluating a file, e.g. `data.system.file.basename` to get the file name being evaluated.

The use case comes from https://github.com/rallyhealth/conftest-policy-packs/issues/10 where we want to enforce a policy against NodeJS `package.json` files, but not other JSON files. The only requirements for the contents of a `package.json` file is that the top-level fields contain `name` and `version`, which are common and are found in many other types of JSON files. The ideal solution would be for the policy to check if the file it is evaluating has a name exactly matching `package.json`.

**Comment by jalseth** [comment] 2021-09-01 04:06
Hi @artis3n. It would be possible to add this, but it may make more sense to use existing tooling. For example, if you place your NPM related policies into a Rego package named `npm` you could do the following:

```sh
find . -name "package.json" -exec conftest test --namespace npm {} \;
```

This would test all `package.json` files against policies in the `npm` namespace. Would this work for you?

**Comment by artis3n** [comment] 2021-09-01 11:51
In our case, no, we are scanning all arbitrary files in a commit in our org. We do prune that to collect the file types that are eligible to be scanned - it's something like all .yml, .Jason, .tf, Dockerfile, excluding .GitHub/, and some stuff like that. But not individual rounds, we gather all eligible files and scan them together with --all-namespaces.

Described vaguely in the readme https://github.com/rallyhealth/conftest-policy-packs . Will be sharing more details about the program we set up at SnykCon in October :) but for the moment that's the only link I have to share.

**Comment by jalseth** [comment] 2021-09-11 17:50
That makes sense, I can take a look at adding this. I think we would want to use `data.conftest` though just to be sure there are no collisions with any user-supplied data. This also appears to be a duplicate of #65.

**Comment by artis3n** [comment] 2021-09-13 02:27
Yeah, this does look like a duplicate. Fine to close if you'd like to encapsulate this in that issue.

**Comment by jalseth** [comment] 2021-09-13 23:27
Added in #610 and it will be included in the next release.

**Closed by jalseth** 2021-09-13 23:27 UTC
Labels: enhancement

**Comment by jalseth** [comment] 2021-09-18 18:19
@artis3n conftest v0.28.0 has been released with this included
